name: DemoPlugin
version: '${project.version}'
main: pl.coronacreeper.Main
api-version: 1.19
authors: [ CoronaCreeper ]
description: Plugin demonstracyjny
commands:
  fly:
    permission: demo.fly
  enderchest:
    permission: demo.ec
    aliases:
      - ec
      - ender
  spawn:
    permission: demo.spawn
